# Generated by Django 5.2.4 on 2025-07-24 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='actual_completion_date',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='timeline',
        ),
        migrations.AddField(
            model_name='goals',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goals',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goals',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='goals',
            name='status',
            field=models.CharField(choices=[('not started', 'Not started'), ('in progress', 'In progress'), ('completed', 'Completed')], default='2025-07-01', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goals',
            name='timeframe',
            field=models.CharField(choices=[('long-term', 'Long-term'), ('short-term', 'Short-term')], default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goals',
            name='planned_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('challenges', models.TextField(default='No challenge indicated')),
                ('lessons', models.TextField(default='No lesson indicated')),
                ('proposed_action', models.TextField(default='No proposed action')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.goals')),
            ],
        ),
    ]
