# Generated by Django 5.2.4 on 2025-07-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goals_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='priority',
            field=models.CharField(choices=[('urgent, important', 'Urgent and important(Immediate action needed) '), ('urgent, not important', 'Urgent and  not important (Schedulable)'), ('not urgent, important', 'Not urgent but important (Delegatable)'), ('not urgent, not important', 'Not urgent and not important (Eliminatable)')], max_length=255, null=True),
        ),
    ]
