# Generated by Django 5.2.4 on 2025-07-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_alter_goals_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
