# Generated by Django 5.2.4 on 2025-08-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_analysis_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analysis',
            new_name='Review',
        ),
    ]
