# Generated by Django 5.2.4 on 2026-02-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_rename_goals_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
