# Generated by Django 5.2.4 on 2026-02-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_rename_date_created_goal_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goal',
            table='goals',
        ),
    ]
