# Generated by Django 5.2.4 on 2026-02-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_alter_goal_name_goal_unique_goal_per_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='completion_date',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='start_date',
            new_name='started_at',
        ),
    ]
