# Generated by Django 5.2.4 on 2026-02-10 14:26

from django.db import migrations, models
from django.utils import timezone


def change_date_fields_to_datetime(apps, schema_editor):
    Goal = apps.get_model('goals', 'Goal')
    for goal in Goal.objects.all():
        if goal.created_at:
            goal.created_at = timezone.make_aware(timezone.datetime.combine(
                goal.created_at, timezone.datetime.min.time()))
        if goal.started_at:
            goal.started_at = timezone.make_aware(timezone.datetime.combine(
                goal.started_at, timezone.datetime.min.time()))
        if goal.completed_at:
            goal.completed_at = timezone.make_aware(timezone.datetime.combine(
                goal.completed_at, timezone.datetime.min.time()))
        goal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_rename_completion_date_goal_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='started_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='completed_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.RunPython(change_date_fields_to_datetime,
                             migrations.RunPython.noop)
    ]
