# Generated by Django 5.2.4 on 2026-02-16 14:42

from django.db import migrations, models
from django.utils import timezone


def change_planned_completion_date_to_datetime(apps, schema_editor):
    Goal = apps.get_model('goals', 'Goal')
    for goal in Goal.objects.all():
        if goal.planned_completion_date:
            goal.planned_completion_date = timezone.make_aware(
                timezone.datetime.combine(goal.planned_completion_date, timezone.datetime.min.time()))
        goal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0015_alter_goal_options_alter_goal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Goal',
            name='planned_completion_date',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.RunPython(
            change_planned_completion_date_to_datetime, migrations.RunPython.noop)
    ]
