# Generated by Django 5.2.4 on 2026-02-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Created this custom migration to fix migration 0016 which had model_name='Goal' 
    (should be 'goal'). Django was forgiving and applied it, but we're correcting it here
    to follow proper naming conventions.
    """

    dependencies = [
        ('goals', '0017_alter_goal_user'),
    ]

    operations = [
        # Reapplying AlterField with the correct model-name, 'goal' in lowercase.
        migrations.AlterField(
            model_name='goal',
            name='planned_completion_date',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
