# Generated by Django 5.2.4 on 2026-02-18 14:14

from django.db import migrations, models


def migrate_priority_data(apps, schema_editor):
    """ This is a forward function that will transfer the data 
    from the deleted priority field into the new urgency and importance fields"""
    Goal = apps.get_model('goals', 'Goal')

    for goal in Goal.objects.all():
        if goal.priority:
            # map old priority values to urgency and importance
            priority_map = {
                "urgent, important": ("urgent", "important"),
                "urgent, not important": ("urgent", "not_important"),
                "not urgent, important": ("not_urgent", "important"),
                "not urgent, not important": ("not_urgent", "not_important"),
            }
            # pick/define urgency and importance values from priority_map
            urgency, importance = priority_map.get(goal.priority, (None, None))
            goal.urgency = urgency
            goal.importance = importance
            goal.save()


def reverse_migration(apps, schema_editor):
    """To reverse urgency and importance fields back to priority"""
    Goal = apps.get_model('goals', 'Goal')

    reverse_map = {
        ("urgent", "important"): "urgent, important",
        ("urgent", "not_important"): "urgent, not important",
        ("not_urgent", "important"): "not urgent, important",
        ("not_urgent", "not_important"): "not urgent, not important",
    }

    for goal in Goal.objects.all():
        if goal.urgency and goal.importance:
            key = (goal.urgency, goal.importance)
            goal.priority = reverse_map.get(key)
        elif goal.urgency and not goal.importance:
            # we shall assume importance is "not_important" where it has not been set
            key = (goal.urgency, "not_important")
            goal.priority = reverse_map.get(key)
        elif goal.importance and not goal.urgency:
            # # we shall assume urgency is "not_urgent" where it has not been set
            key = ("not_urgent", goal.importance)
            goal.priority = reverse_map.get(key)
        else:
            # If neither value is set, priority can't be set
            goal.priority = None
        goal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0018_fix_migration_16_model_name'),
    ]

    operations = [
        # step 1: add new 'urgency' field
        migrations.AddField(
            model_name='goal',
            name='urgency',
            field=models.CharField(
                choices=[('urgent', 'Urgent'),
                         ('not_urgent', 'Not Urgent')],
                max_length=255, null=True, blank=True,),
        ),
        # step 2: add new 'importance' field
        migrations.AddField(
            model_name='goal',
            name='importance',
            field=models.CharField(
                choices=[('important', 'Important'),
                         ('not_important', 'Not Important')],
                max_length=255, null=True, blank=True,),
        ),
        # step 3: migrate data from 'priority' to 'urgency' and 'importance'
        migrations.RunPython(migrate_priority_data, reverse_migration),
        # step 4: Alter the timeframe field to use new textchoices
        migrations.AlterField(
            model_name='goal',
            name='timeframe',
            field=models.CharField(
                choices=[('long_term', 'Long-term'),
                         ('short_term', 'Short-term')], max_length=255,),
        ),
        # step 5: Alter the status field to use new textchoices
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(
                choices=[
                    ('not_started', 'Not started'),
                    ('in_progress', 'In progress'),
                    ('completed', 'Completed'),
                    ('abandoned', 'Abandoned')
                ],
                max_length=255,),
        ),
        # step 6: Remove priority field
        migrations.RemoveField(
            model_name='goal',
            name='priority',
        ),

    ]
