# Generated by Django 5.2.4 on 2026-02-20 05:40

from django.db import migrations


def migrate_timeframe_and_status_data(apps, schema_editor):
    """ Convert timeframe and status fields to new textchoices values"""
    Goal = apps.get_model('goals', 'Goal')

    # Update old timeframe values with new textchoices(hyphen to underscore)
    Goal.objects.filter(timeframe='long-term').update(timeframe='long_term')
    Goal.objects.filter(timeframe='short-term').update(timeframe='short_term')

    # Update only affected status values with new textchoices (space to underscore)
    Goal.objects.filter(status='not started').update(status='not_started')
    Goal.objects.filter(status='in progress').update(status='in_progress')


def reverse_data_migration_for_timeframe_and_status(apps, schema_editor):
    """Reverse timeframe and status values into previous choices format"""
    Goal = apps.get_model('goals', 'Goal')

    # Reverse timeframe (underscore to hyphen)
    Goal.objects.filter(timeframe='long_term').update(timeframe='long-term')
    Goal.objects.filter(timeframe='short_term').update(timeframe='short-term')

    # Reverse status (underscore to space)
    Goal.objects.filter(status='not_started').update(status='not started')
    Goal.objects.filter(status='in_progress').update(status='in progress')


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0019_replace_priority_with_urgency_importance'),
    ]

    operations = [
        migrations.RunPython(
            migrate_timeframe_and_status_data,
            reverse_data_migration_for_timeframe_and_status
        ),
    ]
