# Generated by Django 5.2.4 on 2026-02-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0020_migrate_timeframe_and_status_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
