# Generated by Django 5.2.4 on 2026-03-06 11:58

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0021_delete_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='goal',
            name='importance',
            field=models.CharField(blank=True, choices=[('important', 'Important'), ('not_important', 'Not important')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='timeframe',
            field=models.CharField(choices=[('long_term', 'Long term'), ('short_term', 'Short term')], max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='urgency',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('not_urgent', 'Not urgent')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(default='No description provided')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.goal')),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeRemediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(default='No description added')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('remediated_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.challenge')),
            ],
            options={
                'db_table': 'remediations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Win',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(default='No description added')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.goal')),
            ],
            options={
                'db_table': 'wins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.UniqueConstraint(models.F('goal'), django.db.models.functions.text.Lower('title'), name='unique_challenge_per_goal'),
        ),
        migrations.AddConstraint(
            model_name='challengeremediation',
            constraint=models.UniqueConstraint(models.F('challenge'), django.db.models.functions.text.Lower('title'), name='unique_remediation_per_challenge'),
        ),
        migrations.AddConstraint(
            model_name='win',
            constraint=models.UniqueConstraint(models.F('goal'), django.db.models.functions.text.Lower('title'), name='unique_win _per_goal'),
        ),
    ]
