# Generated by Django 5.2.4 on 2026-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0022_alter_goal_options_alter_goal_importance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('career', 'Career'), ('personal_growth', 'Personal growth'), ('upskilling', 'Upskilling'), ('finances', 'Finances'), ('health', 'Health'), ('diet', 'Diet'), ('fitness', 'Fitness'), ('mental_health', 'Mental health'), ('recovery', 'Recovery'), ('spirituality', 'Spirituality'), ('creativity', 'Creativity'), ('relationships', 'Relationships'), ('parenting', 'Parenting'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
