# Generated by Django 5.2.4 on 2026-03-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0023_goal_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengeremediation',
            options={'ordering': ['-created_at']},
        ),
    ]
