# Generated by Django 5.2.4 on 2026-03-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0024_alter_challengeremediation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challengeremediation',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, choices=[('career', 'Career'), ('personal_growth', 'Personal growth'), ('upskilling', 'Upskilling'), ('finances', 'Finances'), ('health', 'Health'), ('diet', 'Diet'), ('fitness', 'Fitness'), ('mental_health', 'Mental health'), ('recovery', 'Recovery'), ('spirituality', 'Spirituality'), ('creativity', 'Creativity'), ('relationships', 'Relationships'), ('parenting', 'Parenting'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='importance',
            field=models.CharField(blank=True, choices=[('important', 'Important'), ('not_important', 'Not important')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='timeframe',
            field=models.CharField(blank=True, choices=[('long_term', 'Long term'), ('short_term', 'Short term')], max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='urgency',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('not_urgent', 'Not urgent')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='win',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
