# Generated by Django 5.2.4 on 2026-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0025_alter_challenge_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
