# Generated by Django 5.2.4 on 2026-03-25 11:16

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0026_goal_abandoned_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goal',
            name='unique_goal_per_user',
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(models.F('user'), django.db.models.functions.text.Lower('name'), name='unique_goal_per_user'),
        ),
    ]
