# Generated by Django 5.2.4 on 2026-03-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0027_remove_goal_unique_goal_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='remediability',
            field=models.CharField(blank=True, choices=[('remediable_currently', 'Remediable in current goal'), ('remediable_future', 'Remediable only in future occurrences'), ('irremediable', 'Irremediable(completely unfixable)')], max_length=100),
        ),
    ]
