# Generated by Django 5.2.4 on 2026-03-25 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0028_challenge_remediability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeremediation',
            name='challenge',
            field=models.ForeignKey(limit_choices_to={'remediability': 'remediable_currently'}, on_delete=django.db.models.deletion.CASCADE, to='goals.challenge'),
        ),
    ]
