# Generated by Django 5.2.4 on 2026-04-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0029_alter_challengeremediation_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='goals.goal'),
        ),
    ]
