# Generated by Django 5.2.4 on 2026-04-09 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0030_alter_challenge_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeremediation',
            name='challenge',
            field=models.ForeignKey(limit_choices_to={'remediability': 'remediable_currently'}, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_remediations', to='goals.challenge'),
        ),
        migrations.AlterField(
            model_name='win',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='goals.goal'),
        ),
    ]
