# Generated by Django 6.0.4 on 2026-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0031_alter_challengeremediation_challenge_alter_win_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='abandonment_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
