# Generated by Django 6.0.4 on 2026-04-30 09:44

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0032_goal_abandonment_reason'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='win',
            name='unique_win _per_goal',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='win',
            constraint=models.UniqueConstraint(models.F('goal'), django.db.models.functions.text.Lower('title'), name='unique_win_per_goal'),
        ),
    ]
