# Generated by Django 6.0.4 on 2026-05-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0033_remove_win_unique_win__per_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='remediability',
            field=models.CharField(blank=True, choices=[('remediable_currently', 'Remediable in current goal'), ('remediable_future', 'Remediable only in future occurrences'), ('irremediable', 'Irremediable(completely unfixable)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='challengeremediation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='importance',
            field=models.CharField(blank=True, choices=[('important', 'Important'), ('not_important', 'Not important')], max_length=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], max_length=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='timeframe',
            field=models.CharField(blank=True, choices=[('long_term', 'Long term'), ('short_term', 'Short term')], max_length=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='urgency',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('not_urgent', 'Not urgent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='win',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
